all:
	pdflatex top; bibtex top; pdflatex top; pdflatex top;
sup: sup.tex
	pdflatex sup; bibtex sup; pdflatex sup; pdflatex sup;
clean:
	rm -f top.out
	rm -f top.aux
	rm -f top.brf
	rm -f top.blg
	rm -f top.log
	rm -f top.bbl
	rm -f *~
	rm -f sup.out
	rm -f sup.aux
	rm -f sup.brf
	rm -f sup.blg
	rm -f sup.log
	rm -f sup.bbl
	rm -f *.log
